# Generated by Django 2.0.5 on 2018-05-30 20:30

from django.db import migrations, models
import django.db.models.deletion
import vins.modelFields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouleurVin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='vins/static/vins/')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Fruit', vins.modelFields.IntegerRangeField(default=2)),
                ('Personalite', vins.modelFields.IntegerRangeField(default=2)),
                ('Couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vins.CouleurVin')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vins.Region')),
                ('Repas', models.ManyToManyField(to='vins.Repas')),
            ],
        ),
    ]
